spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bom_consultorio_db
    username: bom_app
    password: bom_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
